apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
spec:
  selector:
    matchLabels:
      app: django-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: backend
        image: paularinze/django-backend:v1
        imagPullPolcicy: Always
        ports:
        - containerPort: 80
