apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  # namespace: django-namespace
  labels:
    app: django-backend
spec:
  selector:
    matchLabels:
      app: django-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
      - name: django-backend
        image: paularinze/django-backend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      
